# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Lint + Test + Build + Docs (${{ matrix.package }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - auth0-acul-js
          - auth0-acul-react
          - auth0-acul-angular
          - auth0-acul-vue
          - auth0-acul-svelte
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies at root
        run: npm install

      - name: Lint
        run: npm run lint --if-present
        working-directory: packages/${{ matrix.package }}

      - name: Run tests
        run: npm run test --if-present
        working-directory: packages/${{ matrix.package }}

      - name: Build
        run: npm run build:local --if-present
        working-directory: packages/${{ matrix.package }}

      - name: Generate docs
        run: npm run docs --if-present
        working-directory: packages/${{ matrix.package }}
