name: Monorepo Release

on:
  # Tag-based release (for direct tag pushes, e.g. auth0-acul-js@1.2.3)
  push:
    tags:
      - 'auth0-acul-*@*'

  # PR-based release (for merging release branches, e.g. release/auth0-acul-js/v1.2.3)
  pull_request:
    branches:
      - 'release/*/v*'
    types:
      - closed

  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    # For PR-based: only run if PR was merged
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install deps
        run: npm install

      # Parse package name and version from tag or branch
      - name: Parse version and package
        id: meta
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            NAME=$(echo $TAG | cut -d@ -f1)
            VERSION=$(echo $TAG | cut -d@ -f2)
          else
            BRANCH="${{ github.event.pull_request.base.ref }}"
            NAME=$(echo $BRANCH | cut -d'/' -f2)
            VERSION=$(echo $BRANCH | cut -d'/' -f3 | sed 's/^v//')
          fi
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check tag exists (tag-based only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/tag-exists
        with:
          tag: ${{ github.ref_name }}

      - name: Build
        uses: ./.github/actions/build
        with:
          working-directory: packages/${{ steps.meta.outputs.name }}

      - name: Publish to NPM
        uses: ./.github/actions/npm-publish
        with:
          working-directory: packages/${{ steps.meta.outputs.name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: ./.github/actions/release-create
        with:
          tag: ${{ github.ref_name }}
          name: ${{ steps.meta.outputs.name }}
          version: ${{ steps.meta.outputs.version }}